### ISSUE TITLE
Design a front page for app.

### ISSUE THREAD

**Issue by IamRavikantSingh** [IamRavikantSingh/scoreboard#6]
Currently, this app does not show anything on the "/ " route. So design a page for it with all present routes in the app.

**Comment by arashemadi** [comment]
hello @IamRavikantSingh ... can you please elaborate? I like to work on this, but I don't know what you exactly mean by "designing a page"...

**Comment by IamRavikantSingh** [comment]
> hello @IamRavikantSingh ... can you please elaborate? I like to work on this, but I don't know what you exactly mean by "designing a page"...

Actually If you start the app you will see nothing because there is nothing on "\" route. Currently we need to put the actual URL in browser to navigate to working routes for using the app. We need a page which can be shown at the initial page of app.

**Comment by IamRavikantSingh** [comment]
Yes, go on👍
